### ISSUE TITLE
Infinite loop with duplicate vertex

### ISSUE THREAD

**Issue by sammchardy** [lycantropos/bentley_ottmann#12]
This code snippet will cause an infinite loop

```
line_segment_coords = [
    ((116.19507998, -33.58039633), (116.19507998, -33.58039633)),
    ((116.19507998, -33.58039633), (116.19513912, -33.58040619)),
    ((116.19513912, -33.58040619), (116.19513363, -33.58043912)),
    ((116.19513363, -33.58043912), (116.19507545, -33.58042942)),
    ((116.19507545, -33.58042942), (116.19508094, -33.58039649)),
    ((116.19508094, -33.58039649), (116.19507998, -33.58039633))
]
intersections = segments_intersections(line_segment_coords)
```

Removing the first element of `line_segment_coords` allows `segments_intersections` to complete.

**Comment by lycantropos** [comment]
Thanks for a reproducible example, investigating right now

**Comment by lycantropos** [comment]
Oh, I see, we have a degenerate segment, which causes an infinite loop, because it intersects another segment in itself and then added again to the events queue

**Comment by lycantropos** [comment]
I'm going to add check for degeneracies and raise a `ValueError` in case of occurrence, feel free to comment in PR #13.
