### ISSUE TITLE
segments_intersections missing from v 7.1.0 ?

### ISSUE THREAD

**Issue by nealeyoung** [lycantropos/bentley_ottmann#20]
I was using the routine segments_intersections from bentley_ottmann.planar v 6.0.0 .  I can't find it in v 7.1.0.  Is it gone?  Relocated?  Thank you!

**Comment by lycantropos** [comment]
Hi @nealeyoung, what was the main use-case of yours? I removed it because it wasn't used in other libraries of mine.

**Comment by nealeyoung** [comment]
For planarizing graphs.  (We have road networks that are almost planar.  We convert them into planar graphs by finding edge crossings and "merging" them -- introducing a new node for their intersection and replacing each crossing edge by two edges with the new node in the middle.)

**Comment by lycantropos** [comment]
so to be clear: can [`segments_to_multisegment` function](https://clip.readthedocs.io/en/latest/#clipping.planar.segments_to_multisegment) work for you case? it merges segments and breaks them in points of intersection

**Comment by nealeyoung** [comment]
Maybe?  I looked but can't tell exactly what that does.  What we need is, given a set of straight-line segments, to return, for every segment L, the set S of points in the interior of L that intersect any other given segment (in their interior or endpoints).  (In the case of collinear overlapping segments, the set S can contain points and subsegments in L.)

The previous routine returned all the intersections (including endpoints of L, which we filtered out for each L).

**Comment by lycantropos** [comment]
then I think you can simply use previous version without updating to the current one

**Comment by sgeotech** [comment]
Hi, is it possible to include segments_intersections function in the future version? It was also very useful for us. The alternative you suggested above does not really work for our setting. Sticking to the previous version works of course. We found your implementation of Bentley-Ottmann algorithm the most stable among existing, and we would like to keep the code up to date. Thanks a lot!

**Comment by ThomasPluck** [comment]
Tbf, given that this library no longer plainly implements:

https://en.wikipedia.org/wiki/Bentley%E2%80%93Ottmann_algorithm

Isn't this library now mislabelled?

Edit:

Like, I used the older version and it did exactly what I needed it to do, why would you remove something useful because... it doesn't gel with the rest of your codebase? 😭

**Comment by lycantropos** [comment]
@ThomasPluck can you elaborate? how not providing a particular function for representing intersections changes the underlying algorithm?

**Comment by ThomasPluck** [comment]
I quote:

>In computational geometry, the Bentley–Ottmann algorithm is a sweep line algorithm for listing all crossing in a set of line segments, i.e. it finds the intersection points (or, simply, intersections) of line segments.


If there is no simple function to do exactly that with your library, it is no longer offering the Bentley-Ottmann algorithm.

We can get into the weeds of "what the algorithm really is" - but when people are looking up your library, they're looking for a simple utility that lets them compute line segment intersections in O(n log n) time without needing to download CGAL or infer from your sparse documentation and possibly an intro lecture to Bentley-Ottmann on how to do this.

From a user perspective, this is like Mercedes saying, "of course we're still selling cars: here's all the pieces that you need to make it".

**Comment by lycantropos** [comment]
Firstly you were saying about
> this library no longer plainly implements

but it does, "plainly" or not -- I tried my best.

>> it finds the intersection points (or, simply, intersections) of line segments

Yes, `bentley_ottmann.core.sweep` function does exactly that.

Now you are saying that

> it is no longer offering the Bentley-Ottmann algorithm

but here's a thing: "offering" and "implementing" are not the same.

This library *implements* and utilizes mentioned algorithm, I see no "mislabelling".

> when people are looking up your library, they're looking for a simple utility that lets them compute line segment intersections

and they are free to do so, they even have multiple ways of approaching this after finding this issue
- use a version `<7.0`,
- implement it themselves (e.g. by copy-pasting),
- fork,
- implement their own version, potentially using this one as a reference.

I'm not going to invest more of my time on supporting the functionality that I do not plan to use, I hope it's clear.

**Comment by ThomasPluck** [comment]
> Yes, bentley_ottmann.core.sweep function does exactly that.

Excellent, can you then clearly document it in the `README` then?

It should be clear from the fact that you've had 4 people complaining about this exact functionality that it isn't clear to users that this modification was made!
